### PR TITLE
Added user profile & audit widgets

### PR DESCRIPTION
**Pull request by nirgur**

### CODE REVIEW

**Comment by omercnet** [comment]
#### 📝 Changed routes:


| [**/audit**](https://nextjs-hackathon-template-pages-jezqf63tf.preview.descope.org/audit) | [**/dashboard**](https://nextjs-hackathon-template-pages-jezqf63tf.preview.descope.org/dashboard) |
|:-:|:-:|
|<a href="https://nextjs-hackathon-template-pages-jezqf63tf.preview.descope.org/audit">Screenshot of /audit</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/66NgXhMFx3q0dzdhZB5HzpND2i6IbXBvWxgpyXG_nNaYAYOzdxqrw4dy1bpyJaGRa49WIVMSdym8dU5zfFN9XA.png">(view full size)</a> |<a href="https://nextjs-hackathon-template-pages-jezqf63tf.preview.descope.org/dashboard">Screenshot of /dashboard</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/Ivb0a6wCxIXUjX_0QLj60e8K8UHIvWpjshn-8jfOviFVy4faAk2WxbOdocVNg2gx6RfUj_vy2mOtEO9MYu2WdA.png">(view full size)</a> |



| [**/profile**](https://nextjs-hackathon-template-pages-jezqf63tf.preview.descope.org/profile) |
|:-:|
|<a href="https://nextjs-hackathon-template-pages-jezqf63tf.preview.descope.org/profile">Screenshot of /profile</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/sejibt66tFaN1BJjKHNM3DHDhMISkIIIv2Vb0FYMyumRILzEgZuNhwBDU0NkYqGJrNEfpOcH2tLKUwPm0iH8DQ.png">(view full size)</a> |







Commit e122ceca7e4e6bf1f6364c767bdb011a8aef3fc5 (https://nextjs-hackathon-template-pages-jezqf63tf.preview.descope.org).

**Comment by nirgur** [comment]
> #### 📝 Changed routes:
> [**/audit**](https://nextjs-hackathon-template-pages-jezqf63tf.preview.descope.org/audit)	[**/dashboard**](https://nextjs-hackathon-template-pages-jezqf63tf.preview.descope.org/dashboard)
> [Screenshot of /audit](https://nextjs-hackathon-template-pages-jezqf63tf.preview.descope.org/audit)
> [(view full size)](https://images.weserv.nl?url=https://sjc.microlink.io/66NgXhMFx3q0dzdhZB5HzpND2i6IbXBvWxgpyXG_nNaYAYOzdxqrw4dy1bpyJaGRa49WIVMSdym8dU5zfFN9XA.png)	[Screenshot of /dashboard](https://nextjs-hackathon-template-pages-jezqf63tf.preview.descope.org/dashboard)
> [(view full size)](https://images.weserv.nl?url=https://sjc.microlink.io/Ivb0a6wCxIXUjX_0QLj60e8K8UHIvWpjshn-8jfOviFVy4faAk2WxbOdocVNg2gx6RfUj_vy2mOtEO9MYu2WdA.png)
> [**/profile**](https://nextjs-hackathon-template-pages-jezqf63tf.preview.descope.org/profile)
> [Screenshot of /profile](https://nextjs-hackathon-template-pages-jezqf63tf.preview.descope.org/profile)
> [(view full size)](https://images.weserv.nl?url=https://sjc.microlink.io/sejibt66tFaN1BJjKHNM3DHDhMISkIIIv2Vb0FYMyumRILzEgZuNhwBDU0NkYqGJrNEfpOcH2tLKUwPm0iH8DQ.png)
> Commit [e122cec](https://github.com/descope-sample-apps/nextjs-hackathon-template-pages/commit/e122ceca7e4e6bf1f6364c767bdb011a8aef3fc5) (https://nextjs-hackathon-template-pages-jezqf63tf.preview.descope.org).

In order to see the widgets, we need to sync this project,
I don't know which project is it and if I have access to it
Do you know how can I find it?

Regarding the dashboard, you need to be logged in, in order to access it
But there is an error when trying to log in, I think some env vars are missing/wrong

**Comment by nirgur** [comment]
@omercnet fixed

**Review by dorsha — APPROVED** [review]

**Comment by gaokevin1** [comment]
@nirgur @dorsha are you guys not seeing errors when you run the vercel preview of this app?

I'm getting issues relating to not being able to access static assets: 
image

To OauthCallbackFailed errors with NextAuth. I assume it's not an env variable issue if it works for both you.

**Comment by nirgur** [comment]
> @nirgur @dorsha are you guys not seeing errors when you run the vercel preview of this app?
> 
> I'm getting issues relating to not being able to access static assets: image
> 
> To OauthCallbackFailed errors with NextAuth. I assume it's not an env variable issue if it works for both you.

I checked again and I'm getting this error also, only when on incognito
It seems like the first URL is missing the flow id

this it the URL that fails
https://static.descope.com/pages/P2RvyUSbOG2KwrxebqHucn5YIXxw/v2-beta/SC2RvyWf9zzWfxfc7pfaTo9JFNStt.html

When refreshing the page it works
This is the URL that works
https://static.descope.com/pages/P2RvyUSbOG2KwrxebqHucn5YIXxw/v2-beta/sign-up-or-in/SC2RvyWf9zzWfxfc7pfaTo9JFNStt.html

**Pull request merged**
